name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - tornado
  - jupyterhub
  - hub
  - name: binderhub
    version: "0.2.0-n978.h2eb8b07"
    repository: https://jupyterhub.github.io/helm-chart
binderhub:
  jupyterhub:
    hub:
      extraConfig:
       myConfig: |
        tornado_settings_values = {
          "websocket_max_message_size": 104857600
          }
        c.KubeSpawner.args = [
          f'--NotebookApp.tornado_settings={tornado_settings_values}'
          ]