name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - tornado
#  - binderhub
  - jupyterhub
  - hub
binderhub:
  jupyterhub:
    hub:
      extraConfig:
        10-binder-customisations: |
          class MyCustomBinderSpawner(BinderSpawner):
              ...

          c.JupyterHub.spawner_class = MyCustomBinderSpawner